services:
  mongo:
    image: mongo:6.0.8
    container_name: largo_mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
    volumes:
      - mongo_data:/data/db
    # Não expor Mongo diretamente ao host por padrão (seguir política de segurança local)
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - largo_net
    restart: unless-stopped

volumes:
  mongo_data:

networks:
  largo_net:
    driver: bridge
